blank_lines_upper_bound = 1
comment_width = 100
condense_wildcard_suffixes = true
edition = "2024"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
hard_tabs = false
hex_literal_case = "Upper"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
max_width = 100
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
use_small_heuristics = "Max"
wrap_comments = true
